server:
    port: 3000
    # error:
        # include-stacktrace: never   #(whether to include stacktrace in response)


productservice:
    type: fakeStoreProductService

    clients: 
        fakestore:
            api:
                url: https://fakestoreapi.com
                paths: 
                    products: /products
